### ISSUE TITLE
在cirru-shell上输入任何字符均报错退出 TypeError: undefined is not a function

### ISSUE THREAD

**Issue by leizongmin** [Cirru/cirru-shell#1]
刚安装 `cirru-shell@0.0.5`

``` bash
$ cirru-shell
cirru> number 1

/usr/local/lib/node_modules/cirru-shell/src/evaluator.js:44
  ast = (parse(code))[0];
         ^
TypeError: undefined is not a function
    at Object.exports.call (/usr/local/lib/node_modules/cirru-shell/src/evaluator.js:44:10)
    at Interface.<anonymous> (/usr/local/lib/node_modules/cirru-shell/src/shell.js:80:28)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.emit (events.js:98:17)
    at emitKey (readline.js:1095:12)
    at ReadStream.onData (readline.js:840:14)
```

**Comment by tiye** [comment]
更新了一下依赖, 应该可以了.
不过这个 Shell 是用来测试的, 并不是 Cirru 语言的 Shell, 另外 cirru-script 的 REPL 直接带在那个包里的.
